### ISSUE TITLE
how can i error handler to sentry, don't use \Yii::$app->get('raven'); before 'throw new \Exception("message");'

### ISSUE THREAD

**Issue by dcb9** [E96/yii2-sentry#2]
how can i error handler to sentry, don't use \Yii::$app->get('raven'); before 'throw new \Exception("message");'

It can not recored to sentry if i don't use 

``` php
\Yii::$app->get('raven'); 
```

before 

``` php
throw new \Exception('bobtest');
```

I want to record every system error. Like: Warning, Exception, Error. 

What should i do?

Thanks.

**Comment by sheershoff** [comment]
It's for adding some extra data into the raven event before the component will handle the exception. However the component will handle this exception and send all the data it gathered to raven. Most probably it is sufficient for you to use it without such call.

**Comment by dcb9** [comment]
Thanks your reply.  :)

How to config `error handle` is use `raven` ?

For example:
Goal: _Config database_

``` php
'db' => [
        'class' => 'yii\db\Connection',
        'dsn' => 'mysql:host=localhost;dbname=db_name',
        'username' => 'username',
        'password' => 'password',
        'charset' => 'utf8',
    ],
```

add above config to app/config/main.php 

I want to know what code was input in `Yii2` to enable it to record error to `Sentry`.

**Comment by dcb9** [comment]
I forgot configure 

``` php
[
    'bootstrap' => ['log', 'raven']
]
```

Sorry for my foolish.
